package model;
// Generated Apr 6, 2017 12:29:42 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Account generated by hbm2java
 */

@Entity
@Table(name = "account")
public class Account  implements java.io.Serializable {

     @Id
     @GeneratedValue
     @Column(name = "id")
     private Integer id;
     
     @Column(name = "username")
     private String username;
     
     @Column(name = "password")
     private String password;
     
     @Column(name = "role")
     private boolean role;

    public Account() {
    }

    public Account(String username, String password, boolean role) {
       this.username = username;
       this.password = password;
       this.role = role;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isRole() {
        return this.role;
    }
    
    public void setRole(boolean role) {
        this.role = role;
    }




}


