package model;
// Generated Apr 6, 2017 12:29:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Product generated by hbm2java
 */

@Entity
@Table(name = "product")
public class Product  implements java.io.Serializable {

     @Id 
     @GeneratedValue
     @Column(name = "id")
     private Integer id;
     
     @Column(name = "name")
     private String name;
     
     @Column(name = "price")
     private int price;
     
     @Column(name = "description")
     private String description;
     
     @Column(name = "discount")
     private float discount;
     
     @Column(name = "created")
     private Date created;
     
     @Column(name = "image")
     private String image;

    public Product() {
    }

    public Product(String name, int price, String description, float discount, Date created, String image) {
       this.name = name;
       this.price = price;
       this.description = description;
       this.discount = discount;
       this.created = created;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


